import type { Destination } from "./destinations";

type Extra = Pick<Destination, "region" | "arrivals" | "airport" | "gettingAround" | "food" | "currency" | "language" | "goodToKnow" | "tours">;

/** Full-guide details for the top-20 cities that already had a short guide. */
export const EXTRAS: Record<string, Extra> = {
  london: {
    region: "Europe", arrivals: "22.7M international visitors (2025)",
    airport: "Heathrow (LHR): Elizabeth line or Heathrow Express to central London in 15–35 min. Also Gatwick, Stansted, Luton and London City.",
    gettingAround: "The Tube, buses and Overground cover everything. Tap a contactless card; fares cap daily and weekly.",
    food: ["Sunday roast in a pub", "Fish and chips", "Afternoon tea", "Curry on Brick Lane", "Borough Market street food"],
    currency: "British pound (GBP)", language: "English",
    goodToKnow: ["Most major museums are free.", "Stand on the right on escalators.", "Weather changes fast; carry a light jacket year-round."],
    tours: [
      { id: "london-royal", name: "Royal London in a day", duration: "Full day", summary: "Palaces, the Changing of the Guard and the Crown Jewels with a private guide.", highlights: ["Buckingham Palace and the guard change", "Westminster Abbey", "Tower of London and Crown Jewels"] },
      { id: "london-harry-potter", name: "Warner Bros. Studio Tour", duration: "Half day", summary: "Round-trip transfer to the Harry Potter studio sets outside London.", highlights: ["Great Hall and Diagon Alley", "Hogwarts Express platform", "Hotel pick-up"] },
      { id: "london-cotswolds", name: "Cotswolds and Oxford", duration: "Full day", summary: "Honey-stone villages and university colleges, small-group.", highlights: ["Bibury and Bourton-on-the-Water", "Oxford colleges", "Country pub lunch"] },
    ],
  },
  paris: {
    region: "Europe", arrivals: "18.3M international visitors (2025) · #1 in Euromonitor's overall city ranking",
    airport: "Charles de Gaulle (CDG): RER B to the center in about 35 min, or taxi at a fixed fare. Orly (ORY) for many European flights.",
    gettingAround: "Metro and RER are fast and frequent. Walk between neighborhoods; the center is compact.",
    food: ["Croissant from a neighborhood bakery", "Steak frites in a bistro", "Falafel in the Marais", "Macarons", "Cheese and wine bar evenings"],
    currency: "Euro (EUR)", language: "French",
    goodToKnow: ["Greet shopkeepers with \"Bonjour\".", "Many museums close Monday or Tuesday.", "Book the Louvre and Eiffel Tower ahead."],
    tours: [
      { id: "paris-louvre", name: "Louvre highlights, skip the line", duration: "2.5 hours", summary: "Mona Lisa, Venus de Milo and the masterpieces with an art historian.", highlights: ["Reserved entry", "Small group", "Headsets included"] },
      { id: "paris-versailles", name: "Versailles palace and gardens", duration: "Half day", summary: "Hall of Mirrors, royal apartments and gardens with transport from Paris.", highlights: ["Priority entrance", "Marie Antoinette's estate option", "Hotel pick-up"] },
      { id: "paris-seine-dinner", name: "Seine dinner cruise", duration: "2.5 hours", summary: "Three-course dinner gliding past lit-up monuments.", highlights: ["Eiffel Tower sparkle", "Live music", "Window table"] },
    ],
  },
  dubai: {
    region: "Middle East", arrivals: "19.5M international visitors (2025)",
    airport: "Dubai International (DXB): Metro Red Line to Downtown in about 30 min; taxis at the terminal. Some airlines use Al Maktoum (DWC).",
    gettingAround: "Metro plus taxis or ride-hailing. Distances are long; it isn't a walking city in summer.",
    food: ["Shawarma", "Emirati machboos", "Camel-milk chocolate", "Brunch at a beach hotel", "Karak tea"],
    currency: "UAE dirham (AED)", language: "Arabic; English widely spoken",
    goodToKnow: ["Weekend is Saturday–Sunday.", "Dress modestly outside beaches and resorts.", "Summer (June–September) often tops 105°F."],
    tours: [
      { id: "dubai-desert", name: "Evening desert safari", duration: "6 hours", summary: "Dune drive, camel ride, sandboarding and dinner at a desert camp.", highlights: ["4x4 dune bashing", "Sunset photo stop", "BBQ dinner and show"] },
      { id: "dubai-abu-dhabi", name: "Abu Dhabi day trip", duration: "Full day", summary: "Sheikh Zayed Grand Mosque and the Louvre Abu Dhabi.", highlights: ["Grand Mosque visit", "Louvre Abu Dhabi", "Private driver"] },
      { id: "dubai-burj", name: "Burj Khalifa at sunset", duration: "2 hours", summary: "Timed sunset entry to the observation decks, then the fountain show.", highlights: ["Levels 124–125", "Sunset slot", "Dubai Fountain"] },
    ],
  },
  bangkok: {
    region: "Asia", arrivals: "30.3M international visitors (2025) · world's most visited city",
    airport: "Suvarnabhumi (BKK): Airport Rail Link to the city in about 30 min. Don Mueang (DMK) for many budget airlines.",
    gettingAround: "BTS Skytrain and MRT avoid traffic; river ferries and tuk-tuks for short hops. Use ride-hailing apps for fair fares.",
    food: ["Pad thai", "Tom yum goong", "Mango sticky rice", "Boat noodles", "Street-side grilled pork (moo ping)"],
    currency: "Thai baht (THB)", language: "Thai",
    goodToKnow: ["Cover shoulders and knees at temples.", "Never speak disrespectfully about the royal family.", "Bargain at markets, not in malls."],
    tours: [
      { id: "bangkok-temples", name: "Grand Palace and temples", duration: "Half day", summary: "Grand Palace, Wat Pho and Wat Arun by longtail boat.", highlights: ["Emerald Buddha", "Reclining Buddha", "River crossing"] },
      { id: "bangkok-food", name: "Chinatown street-food night", duration: "3 hours", summary: "Ten tastings along Yaowarat Road with a local guide.", highlights: ["Michelin-listed stalls", "Tuk-tuk ride", "Dessert stop"] },
      { id: "bangkok-ayutthaya", name: "Ayutthaya ancient capital", duration: "Full day", summary: "UNESCO temple ruins, return by river cruise.", highlights: ["Wat Mahathat Buddha head", "Bang Pa-In palace", "Lunch cruise"] },
    ],
  },
  rome: {
    region: "Europe", arrivals: "#4 in Euromonitor's overall city ranking (2025)",
    airport: "Fiumicino (FCO): Leonardo Express to Termini in 32 min. Ciampino (CIA) for some budget flights.",
    gettingAround: "Walk the historic center; metro and buses for longer trips. Taxis from official ranks.",
    food: ["Cacio e pepe", "Carbonara", "Supplì", "Pizza al taglio", "Gelato"],
    currency: "Euro (EUR)", language: "Italian",
    goodToKnow: ["Vatican sites need shoulders and knees covered.", "Fountains (nasoni) give free drinking water.", "Book the Colosseum and Vatican weeks ahead."],
    tours: [
      { id: "rome-colosseum", name: "Colosseum, Forum and Palatine", duration: "3 hours", summary: "Guided entry including the arena floor.", highlights: ["Arena floor access", "Roman Forum", "Small group"] },
      { id: "rome-vatican", name: "Vatican early entry", duration: "3 hours", summary: "Vatican Museums and Sistine Chapel before the crowds.", highlights: ["Early access slot", "Sistine Chapel", "St. Peter's Basilica"] },
      { id: "rome-amalfi", name: "Pompeii and Amalfi Coast", duration: "Full day", summary: "Ancient Pompeii and the coastal road to Positano.", highlights: ["Pompeii guided walk", "Positano stop", "High-speed train option"] },
    ],
  },
  tokyo: {
    region: "Asia", arrivals: "#3 in Euromonitor's overall city ranking (2025)",
    airport: "Haneda (HND): monorail or Keikyu line to the center in 20–30 min. Narita (NRT): Narita Express in about an hour.",
    gettingAround: "Trains and subway run on the minute. Load a Suica or Pasmo card on your phone.",
    food: ["Sushi at Tsukiji", "Ramen", "Tempura", "Yakitori in Omoide Yokocho", "Convenience-store snacks"],
    currency: "Japanese yen (JPY)", language: "Japanese",
    goodToKnow: ["Tipping isn't customary.", "Keep quiet on trains; no phone calls.", "Carry some cash for small restaurants."],
    tours: [
      { id: "tokyo-highlights", name: "Tokyo highlights with a local", duration: "Full day", summary: "Asakusa, Meiji Shrine, Harajuku and Shibuya by train.", highlights: ["Sensō-ji temple", "Shibuya Crossing", "Train pass included"] },
      { id: "tokyo-fuji", name: "Mt. Fuji and Hakone", duration: "Full day", summary: "Lake Ashi cruise, ropeway and Fuji views.", highlights: ["Fuji 5th Station (seasonal)", "Hakone ropeway", "Lake cruise"] },
      { id: "tokyo-izakaya", name: "Shinjuku izakaya night", duration: "3 hours", summary: "Bar-hopping through Golden Gai and Omoide Yokocho.", highlights: ["Three stops", "Food and drinks", "English-speaking host"] },
    ],
  },
  "new-york": {
    region: "North America", arrivals: "One of the top international destinations in North America",
    airport: "JFK: AirTrain to subway or LIRR, 45–60 min to Midtown. Newark (EWR): AirTrain and NJ Transit. LaGuardia (LGA) for domestic flights.",
    gettingAround: "Subway runs 24/7; tap a contactless card. Walk Manhattan's grid; yellow cabs and ride-hailing everywhere.",
    food: ["New York pizza slice", "Bagel with lox", "Pastrami on rye", "Dumplings in Chinatown", "Cheesecake"],
    currency: "US dollar (USD)", language: "English",
    goodToKnow: ["Tip 18–20% at restaurants.", "Hotel taxes add about 15%.", "Museums like the Met have timed entry."],
    tours: [
      { id: "nyc-helicopter", name: "Manhattan helicopter flight", duration: "20 min", summary: "Statue of Liberty, skyline and Central Park from the air.", highlights: ["Downtown heliport", "Window seat", "Photo stops"] },
      { id: "nyc-liberty", name: "Statue of Liberty and Ellis Island", duration: "Half day", summary: "Ferry, pedestal access and the immigration museum.", highlights: ["Reserved ferry", "Pedestal access", "Guide"] },
      { id: "nyc-broadway", name: "Broadway night", duration: "Evening", summary: "Top show tickets with pre-theater dinner in the Theater District.", highlights: ["Orchestra seats", "Dinner reservation", "Car home option"] },
    ],
  },
};

/** New guides for the rest of the top-20 list. */
export const NEW_GUIDES: Destination[] = [
  {
    slug: "hong-kong", name: "Hong Kong", country: "China (SAR)", iata: ["HKG"], mainAirport: "HKG", region: "Asia",
    arrivals: "23.2M international visitors (2025) · #2 worldwide",
    tagline: "Skyline, harbor and dim sum.",
    intro: "Hong Kong packs one of the world's great skylines, mountain hiking trails and outlying islands into a city that runs on excellent transit.",
    bestTime: "October–December: clear skies and mild temperatures.",
    todo: [
      { title: "Victoria Peak", text: "Ride the Peak Tram for the classic harbor view." },
      { title: "Star Ferry", text: "Cross Victoria Harbour for a few dollars." },
      { title: "Symphony of Lights", text: "Nightly light show from the Tsim Sha Tsui promenade." },
      { title: "Tian Tan Buddha", text: "Ngong Ping cable car to the giant Buddha on Lantau." },
      { title: "Temple Street Night Market", text: "Street food, fortune tellers and bargains." },
      { title: "Dragon's Back hike", text: "Easy ridge trail ending at Shek O beach." },
    ],
    neighborhoods: "Central for business and bars, Tsim Sha Tsui for views and shopping.",
    tip: "Get an Octopus card; it pays for transit, shops and even vending machines.",
    airport: "Hong Kong International (HKG): Airport Express to Central in 24 min.",
    gettingAround: "MTR metro, trams on Hong Kong Island, and ferries to the islands.",
    food: ["Dim sum", "Roast goose", "Egg tarts", "Wonton noodles", "Pineapple bun"],
    currency: "Hong Kong dollar (HKD)", language: "Cantonese and English",
    goodToKnow: ["Typhoon season runs June–September.", "Tap-and-go payments are everywhere.", "Macau is an hour away by ferry or bridge bus."],
    tours: [
      { id: "hk-island", name: "Hong Kong Island and the Peak", duration: "Half day", summary: "Peak Tram, Stanley Market and Aberdeen fishing harbor.", highlights: ["Peak Tram tickets", "Sampan ride", "Stanley Market"] },
      { id: "hk-lantau", name: "Lantau and the Big Buddha", duration: "Full day", summary: "Cable car, Po Lin Monastery and Tai O fishing village.", highlights: ["Crystal cabin option", "Vegetarian monastery lunch", "Stilt houses"] },
      { id: "hk-food", name: "Sham Shui Po food tour", duration: "3 hours", summary: "Local eateries and markets away from the tourist trail.", highlights: ["Eight tastings", "Street markets", "Local guide"] },
    ],
  },
  {
    slug: "macau", name: "Macau", country: "China (SAR)", iata: ["MFM"], mainAirport: "MFM", region: "Asia",
    arrivals: "20.4M international visitors (2025) · fastest-growing in the top 10",
    tagline: "Portuguese heritage meets the world's biggest casinos.",
    intro: "Macau blends a UNESCO-listed Portuguese old town with the glittering resorts of the Cotai Strip.",
    bestTime: "October–December for dry, mild weather.",
    todo: [
      { title: "Ruins of St. Paul's", text: "The iconic church façade in the old town." },
      { title: "Senado Square", text: "Wave-patterned Portuguese paving and colonial buildings." },
      { title: "Cotai Strip", text: "Resorts, shows and replicas of Venice and Paris." },
      { title: "Macau Tower", text: "Views, a skywalk and the world's highest commercial bungee." },
      { title: "A-Ma Temple", text: "The temple that gave Macau its name." },
      { title: "Taipa Village", text: "Colorful lanes, cafés and Portuguese restaurants." },
    ],
    neighborhoods: "Cotai for resorts; the peninsula for the historic center.",
    tip: "Free hotel shuttle buses connect the border, ferry piers and casinos.",
    airport: "Macau International (MFM), or fly into Hong Kong (HKG) and cross by ferry or the bridge bus in about an hour.",
    gettingAround: "Light rail on Taipa and Cotai, buses, taxis and free casino shuttles.",
    food: ["Portuguese egg tart", "Pork chop bun", "African chicken", "Minchi", "Almond cookies"],
    currency: "Macanese pataca (MOP); Hong Kong dollars accepted", language: "Cantonese and Portuguese",
    goodToKnow: ["Casino entry is 21+.", "Weekends are much busier than weekdays.", "Bring your passport to cross from Hong Kong."],
    tours: [
      { id: "macau-heritage", name: "Historic Macau walk", duration: "Half day", summary: "UNESCO old town from Senado Square to the Fortress.", highlights: ["St. Paul's ruins", "Mount Fortress", "Egg-tart tasting"] },
      { id: "macau-from-hk", name: "Macau day trip from Hong Kong", duration: "Full day", summary: "Round-trip ferry, old town and Cotai.", highlights: ["Ferry tickets", "Lunch in Taipa", "Cotai resorts"] },
      { id: "macau-show", name: "House of Dancing Water", duration: "Evening", summary: "Water-stage acrobatics show with premium seats.", highlights: ["Premium seating", "Hotel transfer", "Dinner option"] },
    ],
  },
  {
    slug: "istanbul", name: "Istanbul", country: "Türkiye", iata: ["IST", "SAW"], mainAirport: "IST", region: "Europe / Asia",
    arrivals: "19.7M international visitors (2025)",
    tagline: "Where Europe meets Asia on the Bosphorus.",
    intro: "Istanbul spans two continents, with Byzantine and Ottoman landmarks, grand bazaars and a vibrant food scene.",
    bestTime: "April–May and September–November.",
    todo: [
      { title: "Hagia Sophia", text: "Fifteen centuries of history under one dome." },
      { title: "Blue Mosque", text: "Six minarets and blue İznik tiles; visit outside prayer times." },
      { title: "Topkapı Palace", text: "Sultans' palace, treasury and harem." },
      { title: "Grand Bazaar and Spice Bazaar", text: "Thousands of shops under historic domes." },
      { title: "Bosphorus cruise", text: "Palaces and waterfront mansions between two continents." },
      { title: "Galata and Karaköy", text: "Tower views, cafés and galleries." },
    ],
    neighborhoods: "Sultanahmet for sights, Karaköy or Beyoğlu for food and nightlife.",
    tip: "Get an İstanbulkart for trams, metro and ferries.",
    airport: "Istanbul Airport (IST): M11 metro or Havaist bus, 45–75 min to the center. Sabiha Gökçen (SAW) on the Asian side.",
    gettingAround: "Tram T1 links the main sights; ferries cross between Europe and Asia.",
    food: ["Kebab and pide", "Balık ekmek (fish sandwich)", "Meze", "Baklava", "Turkish breakfast"],
    currency: "Turkish lira (TRY)", language: "Turkish",
    goodToKnow: ["Women cover hair in mosques; scarves are provided.", "Bargaining is expected in bazaars.", "Traffic is heavy; use trams and ferries."],
    tours: [
      { id: "istanbul-old-city", name: "Old City essentials", duration: "Full day", summary: "Hagia Sophia, Blue Mosque, Topkapı and the Grand Bazaar.", highlights: ["Skip-the-line entry", "Licensed guide", "Lunch included"] },
      { id: "istanbul-bosphorus", name: "Bosphorus sunset cruise", duration: "2.5 hours", summary: "Private yacht between Europe and Asia at golden hour.", highlights: ["Private yacht option", "Palaces from the water", "Drinks on board"] },
      { id: "istanbul-cappadocia", name: "Cappadocia balloon getaway", duration: "2 days", summary: "Fly to Cappadocia for a sunrise hot-air balloon flight and cave hotel.", highlights: ["Round-trip flights", "Balloon ride", "Cave hotel night"] },
    ],
  },
  {
    slug: "mecca", name: "Mecca (Makkah)", country: "Saudi Arabia", iata: ["JED"], mainAirport: "JED", region: "Middle East",
    arrivals: "18.7M international visitors (2025)",
    tagline: "Islam's holiest city, for Hajj and Umrah pilgrims.",
    intro: "Mecca is home to the Masjid al-Haram and the Kaaba. Entry to the city is for Muslims only; most visitors come for Umrah or the annual Hajj.",
    bestTime: "Umrah is year-round; Ramadan is the busiest period. Hajj dates follow the Islamic calendar.",
    todo: [
      { title: "Masjid al-Haram", text: "The Grand Mosque and the Kaaba, the center of Umrah and Hajj rites." },
      { title: "Umrah rites", text: "Tawaf around the Kaaba and Sa'i between Safa and Marwah." },
      { title: "Jabal al-Nour", text: "The mountain of the Hira cave." },
      { title: "Mina, Muzdalifah and Arafat", text: "Hajj sites outside the city." },
      { title: "Makkah Museum", text: "History of the Two Holy Mosques." },
      { title: "Madinah", text: "The Prophet's Mosque, about 2.5 hours by high-speed train." },
    ],
    neighborhoods: "Hotels near the Haram (Clock Tower area) save long walks; farther areas use shuttle buses.",
    tip: "Book Umrah through a licensed provider and register on the official Nusuk platform.",
    airport: "Fly into Jeddah (JED); the Haramain high-speed train reaches Mecca in about an hour. Madinah (MED) is the other gateway.",
    gettingAround: "Haramain train between Jeddah, Mecca and Madinah; hotel shuttles and taxis locally.",
    food: ["Mandi", "Kabsa", "Dates and Arabic coffee", "Mutabbaq", "Zamzam water"],
    currency: "Saudi riyal (SAR)", language: "Arabic",
    goodToKnow: ["Non-Muslims may not enter Mecca.", "Hajj requires a Hajj visa through an approved operator.", "Summer temperatures often exceed 110°F."],
    tours: [
      { id: "mecca-umrah", name: "Umrah package", duration: "7–10 days", summary: "Flights, visa support and hotels near the Haram with a licensed Umrah operator.", highlights: ["Hotel near the Haram", "Haramain train tickets", "Group guidance"] },
      { id: "mecca-umrah-madinah", name: "Umrah with Madinah", duration: "10–14 days", summary: "Umrah in Mecca and nights in Madinah near the Prophet's Mosque.", highlights: ["Both holy cities", "Train transfers", "Ziyarat visits"] },
      { id: "mecca-ramadan", name: "Ramadan Umrah", duration: "10 days", summary: "Last ten nights of Ramadan in Mecca.", highlights: ["Early booking", "Iftar arrangements", "Hotel near the Haram"] },
    ],
  },
  {
    slug: "antalya", name: "Antalya", country: "Türkiye", iata: ["AYT"], mainAirport: "AYT", region: "Europe / Asia",
    arrivals: "18.6M international visitors (2025)",
    tagline: "The Turkish Riviera: beaches, ruins and resorts.",
    intro: "Antalya is the gateway to the Turquoise Coast, with an old harbor town, all-inclusive resorts and ancient cities nearby.",
    bestTime: "May–June and September–October; July–August is hot and busy.",
    todo: [
      { title: "Kaleiçi old town", text: "Ottoman houses and the Roman Hadrian's Gate." },
      { title: "Konyaaltı and Lara beaches", text: "Long beaches minutes from the center." },
      { title: "Düden Waterfalls", text: "Falls that drop straight into the sea." },
      { title: "Aspendos", text: "One of the best-preserved Roman theaters." },
      { title: "Perge and Side", text: "Ancient cities along the coast." },
      { title: "Boat trips", text: "Coves and caves along the coastline." },
    ],
    neighborhoods: "Kaleiçi for character; Lara or Belek for resorts.",
    tip: "Many resorts are all-inclusive; compare total cost, not the nightly rate.",
    airport: "Antalya (AYT): 20–30 min by tram or taxi to the center; resort transfers to Belek and Side.",
    gettingAround: "Trams and taxis in the city; transfers or rental cars for the coast.",
    food: ["Piyaz (bean salad)", "Grilled fish", "Gözleme", "Tandır kebab", "Turkish ice cream"],
    currency: "Turkish lira (TRY)", language: "Turkish",
    goodToKnow: ["Summer highs reach 95–100°F.", "Resort season runs April–November.", "Carry cash for village markets."],
    tours: [
      { id: "antalya-boat", name: "Coastal boat day", duration: "Full day", summary: "Swim stops at coves, lunch on board.", highlights: ["Swim stops", "Lunch on board", "Hotel pick-up"] },
      { id: "antalya-ancient", name: "Perge, Aspendos and Side", duration: "Full day", summary: "Three ancient cities with an archaeologist guide.", highlights: ["Aspendos theater", "Side temple of Apollo", "Lunch"] },
      { id: "antalya-pamukkale", name: "Pamukkale thermal terraces", duration: "Full day", summary: "White travertine pools and the ruins of Hierapolis.", highlights: ["Travertine walk", "Cleopatra's Pool option", "Round-trip transfer"] },
    ],
  },
  {
    slug: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia", iata: ["KUL"], mainAirport: "KUL", region: "Asia",
    arrivals: "17.3M international visitors (2025)",
    tagline: "Twin towers, street food and rainforest at the city's edge.",
    intro: "Kuala Lumpur mixes Malay, Chinese and Indian cultures, with great food and easy day trips to caves and highlands.",
    bestTime: "May–July and December–February are typically drier.",
    todo: [
      { title: "Petronas Twin Towers", text: "Skybridge and observation deck; book ahead." },
      { title: "Batu Caves", text: "Hindu temple caves up 272 rainbow steps." },
      { title: "Jalan Alor", text: "The city's best-known street-food strip." },
      { title: "Merdeka Square", text: "Colonial buildings where independence was declared." },
      { title: "KL Forest Eco Park", text: "Canopy walk in the middle of the city." },
      { title: "Chinatown and Central Market", text: "Handicrafts, temples and food." },
    ],
    neighborhoods: "KLCC for the towers, Bukit Bintang for shopping and food.",
    tip: "Use ride-hailing apps; they're cheap and avoid taxi haggling.",
    airport: "KLIA (KUL): KLIA Ekspres to KL Sentral in about 30 min.",
    gettingAround: "LRT, MRT and monorail; ride-hailing for the rest.",
    food: ["Nasi lemak", "Char kway teow", "Roti canai", "Satay", "Teh tarik"],
    currency: "Malaysian ringgit (MYR)", language: "Malay; English widely spoken",
    goodToKnow: ["Afternoon rain showers are common.", "Dress modestly at mosques.", "Malls are air-conditioned escapes from the heat."],
    tours: [
      { id: "kl-city", name: "KL city and Batu Caves", duration: "Half day", summary: "Towers, King's Palace, Merdeka Square and Batu Caves.", highlights: ["Batu Caves", "Photo stops", "Hotel pick-up"] },
      { id: "kl-food", name: "Night food walk", duration: "3 hours", summary: "Jalan Alor and hidden hawker stalls.", highlights: ["Ten tastings", "Local guide", "Dessert stop"] },
      { id: "kl-highlands", name: "Cameron Highlands tea day", duration: "Full day", summary: "Tea plantations and cool mountain air.", highlights: ["Tea estate visit", "Mossy forest", "Private driver"] },
    ],
  },
  {
    slug: "madrid", name: "Madrid", country: "Spain", iata: ["MAD"], mainAirport: "MAD", region: "Europe",
    arrivals: "#2 in Euromonitor's overall city ranking (2025)",
    tagline: "Art, tapas and late nights.",
    intro: "Madrid pairs three world-class art museums with lively plazas and a food culture that runs past midnight.",
    bestTime: "April–June and September–October.",
    todo: [
      { title: "Prado Museum", text: "Velázquez, Goya and El Greco." },
      { title: "Royal Palace", text: "One of Europe's largest royal palaces." },
      { title: "Retiro Park", text: "Rowboats on the lake and the Crystal Palace." },
      { title: "Plaza Mayor and San Miguel Market", text: "Historic square and gourmet tapas market." },
      { title: "Reina Sofía", text: "Picasso's Guernica." },
      { title: "Day trip to Toledo", text: "Medieval city 33 min by high-speed train." },
    ],
    neighborhoods: "Sol and Huertas for sights, Malasaña and Salamanca for local life.",
    tip: "Lunch is at 2pm and dinner after 9pm; plan museum time around that.",
    airport: "Adolfo Suárez Madrid-Barajas (MAD): Metro Line 8 or the Airport Express bus, about 40 min to the center.",
    gettingAround: "Extensive metro; the center is walkable.",
    food: ["Jamón ibérico", "Bocadillo de calamares", "Cocido madrileño", "Churros con chocolate", "Tortilla española"],
    currency: "Euro (EUR)", language: "Spanish",
    goodToKnow: ["Summer afternoons are very hot.", "The Prado has free late-afternoon entry.", "Sunday morning El Rastro flea market."],
    tours: [
      { id: "madrid-prado", name: "Prado masterpieces", duration: "2 hours", summary: "Skip-the-line tour of the Prado's greatest works.", highlights: ["Reserved entry", "Art historian", "Small group"] },
      { id: "madrid-tapas", name: "Tapas and wine crawl", duration: "3 hours", summary: "Four historic taverns in La Latina.", highlights: ["Four bars", "Wine pairings", "Local guide"] },
      { id: "madrid-toledo", name: "Toledo and Segovia", duration: "Full day", summary: "Two UNESCO cities: cathedral, aqueduct and Alcázar.", highlights: ["Roman aqueduct", "Toledo cathedral", "Transport included"] },
    ],
  },
  {
    slug: "milan", name: "Milan", country: "Italy", iata: ["MIL", "MXP", "LIN", "BGY"], mainAirport: "MXP", region: "Europe",
    arrivals: "#5 in Euromonitor's overall city ranking (2025)",
    tagline: "Fashion, design and The Last Supper.",
    intro: "Milan is Italy's style capital, with a spectacular cathedral, Leonardo's Last Supper and lakes an hour away.",
    bestTime: "April–June and September–October.",
    todo: [
      { title: "Duomo di Milano", text: "Climb to the rooftop among the spires." },
      { title: "The Last Supper", text: "Leonardo's masterpiece; tickets sell out weeks ahead." },
      { title: "Galleria Vittorio Emanuele II", text: "Glass-roofed 19th-century arcade." },
      { title: "Brera", text: "Art gallery and cobbled streets." },
      { title: "Navigli canals", text: "Aperitivo along the canals at sunset." },
      { title: "Lake Como", text: "About an hour by train." },
    ],
    neighborhoods: "Duomo area for sights; Brera or Navigli for evenings.",
    tip: "Aperitivo (around 6–9pm) often includes a food buffet with your drink.",
    airport: "Malpensa (MXP): Malpensa Express to Cadorna or Centrale in about 50 min. Linate (LIN) is closer to town.",
    gettingAround: "Metro and trams; high-speed trains to Venice, Florence and Rome.",
    food: ["Risotto alla milanese", "Cotoletta alla milanese", "Panettone", "Aperitivo", "Gelato"],
    currency: "Euro (EUR)", language: "Italian",
    goodToKnow: ["Fashion weeks fill hotels in February and September.", "Book The Last Supper as early as possible.", "Many shops close in August."],
    tours: [
      { id: "milan-last-supper", name: "Last Supper and Duomo", duration: "3 hours", summary: "Guaranteed Last Supper entry plus the cathedral.", highlights: ["Guaranteed tickets", "Duomo rooftop option", "Guide"] },
      { id: "milan-como", name: "Lake Como and Bellagio", duration: "Full day", summary: "Lakeside towns by boat.", highlights: ["Private boat option", "Bellagio", "Train or coach"] },
      { id: "milan-fashion", name: "Fashion district shopping", duration: "Half day", summary: "Personal shopper through the Quadrilatero della Moda.", highlights: ["Personal stylist", "Boutique access", "Tax-free help"] },
    ],
  },
  {
    slug: "singapore", name: "Singapore", country: "Singapore", iata: ["SIN"], mainAirport: "SIN", region: "Asia",
    arrivals: "#9 in Euromonitor's overall city ranking (2025)",
    tagline: "Garden city, hawker food, spotless and easy.",
    intro: "Singapore is compact, safe and green, with futuristic gardens, diverse neighborhoods and some of the world's best street food.",
    bestTime: "February–April tends to be drier; it's warm year-round.",
    todo: [
      { title: "Gardens by the Bay", text: "Supertrees, Cloud Forest and the nightly light show." },
      { title: "Marina Bay Sands", text: "Observation deck and skyline views." },
      { title: "Hawker centres", text: "Maxwell and Lau Pa Sat for cheap, excellent food." },
      { title: "Sentosa", text: "Beaches, Universal Studios and attractions." },
      { title: "Chinatown, Little India, Kampong Glam", text: "Three neighborhoods, three cultures." },
      { title: "Singapore Zoo and Night Safari", text: "Open-concept zoo in the rainforest." },
    ],
    neighborhoods: "Marina Bay for views, Tiong Bahru or Chinatown for character.",
    tip: "Tap a contactless card on MRT and buses; no ticket needed.",
    airport: "Changi (SIN): MRT to the city in about 45 min, taxi in 20–25. Don't miss the Jewel waterfall.",
    gettingAround: "MRT and buses are fast and cheap; taxis are metered.",
    food: ["Hainanese chicken rice", "Chili crab", "Laksa", "Satay", "Kaya toast"],
    currency: "Singapore dollar (SGD)", language: "English, Mandarin, Malay, Tamil",
    goodToKnow: ["Strict rules: no littering, no chewing gum sales.", "Tipping isn't expected.", "Carry an umbrella for sudden rain."],
    tours: [
      { id: "sg-night", name: "Singapore by night", duration: "4 hours", summary: "River cruise, Gardens by the Bay light show and hawker dinner.", highlights: ["Bumboat cruise", "Supertree show", "Hawker dinner"] },
      { id: "sg-food", name: "Hawker food tour", duration: "3 hours", summary: "Chinatown and Tiong Bahru tastings.", highlights: ["Michelin hawker stall", "Eight tastings", "Local guide"] },
      { id: "sg-sentosa", name: "Sentosa island day", duration: "Full day", summary: "Cable car, beaches and Universal Studios option.", highlights: ["Cable car", "Beach club", "Park tickets option"] },
    ],
  },
  {
    slug: "seoul", name: "Seoul", country: "South Korea", iata: ["SEL", "ICN", "GMP"], mainAirport: "ICN", region: "Asia",
    arrivals: "#10 in Euromonitor's overall city ranking (2025)",
    tagline: "Palaces, K-culture and all-night food.",
    intro: "Seoul combines Joseon-era palaces, hip neighborhoods, K-beauty and K-pop, and a food scene that never sleeps.",
    bestTime: "April–May (blossoms) and September–November (autumn colors).",
    todo: [
      { title: "Gyeongbokgung Palace", text: "Free entry if you wear a hanbok." },
      { title: "Bukchon Hanok Village", text: "Traditional houses between two palaces." },
      { title: "N Seoul Tower", text: "Cable car up Namsan for city views." },
      { title: "Myeongdong", text: "Street food and K-beauty shopping." },
      { title: "Hongdae", text: "Indie music, cafés and nightlife." },
      { title: "DMZ", text: "Guided day trip to the border." },
    ],
    neighborhoods: "Myeongdong for convenience, Insadong for tradition, Hongdae for nightlife.",
    tip: "Get a T-money card; it works on subway, buses and taxis.",
    airport: "Incheon (ICN): AREX express train to Seoul Station in 43 min. Gimpo (GMP) is closer for some routes.",
    gettingAround: "One of the world's best subway systems; signs in English.",
    food: ["Korean BBQ", "Bibimbap", "Fried chicken and beer", "Tteokbokki", "Gwangjang Market bindaetteok"],
    currency: "South Korean won (KRW)", language: "Korean",
    goodToKnow: ["Many sites close on Monday or Tuesday.", "Local map apps work better than Google Maps.", "Tipping isn't customary."],
    tours: [
      { id: "seoul-dmz", name: "DMZ and JSA tour", duration: "Full day", summary: "Tunnels, observatory and the border area with a licensed guide.", highlights: ["Third Tunnel", "Dora Observatory", "Passport required"] },
      { id: "seoul-palace", name: "Palaces in hanbok", duration: "Half day", summary: "Hanbok rental, Gyeongbokgung and Bukchon with a photographer.", highlights: ["Hanbok rental", "Guard ceremony", "Photo session"] },
      { id: "seoul-kpop", name: "K-pop and K-beauty day", duration: "Full day", summary: "Agency districts, dance class and a skincare clinic.", highlights: ["Dance lesson", "Gangnam tour", "Skincare session"] },
    ],
  },
  {
    slug: "osaka", name: "Osaka", country: "Japan", iata: ["OSA", "KIX", "ITM"], mainAirport: "KIX", region: "Asia",
    arrivals: "#11 in Euromonitor's overall city ranking (2025)",
    tagline: "Japan's kitchen: street food, neon and a castle.",
    intro: "Osaka is loud, friendly and food-obsessed, and the best base for day trips to Kyoto, Nara and Kobe.",
    bestTime: "March–May and October–November.",
    todo: [
      { title: "Dotonbori", text: "Neon canal district and street food." },
      { title: "Osaka Castle", text: "Castle museum and park, lovely in cherry-blossom season." },
      { title: "Universal Studios Japan", text: "Including Super Nintendo World." },
      { title: "Kuromon Market", text: "Seafood and snacks." },
      { title: "Umeda Sky Building", text: "Floating Garden observatory." },
      { title: "Nara day trip", text: "Giant Buddha and free-roaming deer, 45 min away." },
    ],
    neighborhoods: "Namba for food and nightlife, Umeda for transport links.",
    tip: "An ICOCA or Suica card works on trains across the region.",
    airport: "Kansai (KIX): Nankai rapi:t to Namba in about 40 min. Itami (ITM) for domestic flights.",
    gettingAround: "Metro and JR lines; Kyoto is 15–30 min by train.",
    food: ["Takoyaki", "Okonomiyaki", "Kushikatsu", "Kobe beef (nearby)", "Kitsune udon"],
    currency: "Japanese yen (JPY)", language: "Japanese",
    goodToKnow: ["Stand on the right on escalators here (left in Tokyo).", "Book USJ express passes ahead.", "Cash still matters at small shops."],
    tours: [
      { id: "osaka-food", name: "Dotonbori street-food night", duration: "3 hours", summary: "Takoyaki, okonomiyaki and kushikatsu with a local.", highlights: ["Six stops", "Drinks included", "Neon photo spots"] },
      { id: "osaka-nara", name: "Nara and Uji", duration: "Full day", summary: "Tōdai-ji's Great Buddha, deer park and matcha in Uji.", highlights: ["Great Buddha Hall", "Deer park", "Tea ceremony"] },
      { id: "osaka-kobe", name: "Kobe beef and sake", duration: "Half day", summary: "Sake brewery tour and a Kobe beef lunch.", highlights: ["Sake tasting", "Kobe beef teppanyaki", "Train pass"] },
    ],
  },
  {
    slug: "taipei", name: "Taipei", country: "Taiwan", iata: ["TPE", "TSA"], mainAirport: "TPE", region: "Asia",
    arrivals: "#15 in Euromonitor's overall city ranking (2025)",
    tagline: "Night markets, temples and mountain hot springs.",
    intro: "Taipei is easygoing and safe, with superb night markets, hiking at the city's edge and hot springs a metro ride away.",
    bestTime: "October–April; summers are hot with typhoon risk.",
    todo: [
      { title: "Taipei 101", text: "Observatory and the giant tuned mass damper." },
      { title: "Night markets", text: "Shilin, Raohe and Ningxia for local snacks." },
      { title: "National Palace Museum", text: "Treasures of Chinese imperial collections." },
      { title: "Elephant Mountain", text: "Short hike to the classic Taipei 101 view." },
      { title: "Beitou hot springs", text: "Public baths at the end of the metro line." },
      { title: "Jiufen", text: "Hillside old town with teahouses." },
    ],
    neighborhoods: "Da'an or Zhongshan for food and transit.",
    tip: "An EasyCard pays for metro, buses and convenience stores.",
    airport: "Taoyuan (TPE): Airport MRT express to Taipei Main Station in about 35 min. Songshan (TSA) is in the city.",
    gettingAround: "Clean, simple metro; YouBike shared bikes everywhere.",
    food: ["Beef noodle soup", "Xiaolongbao", "Bubble tea", "Gua bao", "Pepper buns"],
    currency: "New Taiwan dollar (TWD)", language: "Mandarin",
    goodToKnow: ["No eating or drinking on the metro.", "Convenience stores sell almost everything.", "Typhoon season runs July–September."],
    tours: [
      { id: "taipei-jiufen", name: "Jiufen and Shifen", duration: "Full day", summary: "Old-street teahouses and sky lanterns at Shifen.", highlights: ["Sky lantern", "Shifen waterfall", "Teahouse stop"] },
      { id: "taipei-night-market", name: "Night market food tour", duration: "3 hours", summary: "Raohe or Ningxia market with a local foodie.", highlights: ["Ten tastings", "Stinky tofu dare", "Temple stop"] },
      { id: "taipei-taroko", name: "Taroko Gorge", duration: "Full day", summary: "Marble canyon by express train and private driver.", highlights: ["Train tickets", "Gorge trails (subject to access)", "Private driver"] },
    ],
  },
  {
    slug: "kyoto", name: "Kyoto", country: "Japan", iata: ["UKY"], mainAirport: "KIX", region: "Asia",
    arrivals: "#19 in Euromonitor's overall city ranking (2025)",
    tagline: "Temples, gardens and geisha lanes.",
    intro: "Kyoto was Japan's capital for over a thousand years and keeps some 1,600 temples, classic gardens and wooden townhouses.",
    bestTime: "Late March–April (cherry blossoms) and November (autumn leaves).",
    todo: [
      { title: "Fushimi Inari", text: "Thousands of red torii gates; go early." },
      { title: "Kinkaku-ji", text: "The Golden Pavilion reflected in its pond." },
      { title: "Arashiyama", text: "Bamboo grove and the monkey park." },
      { title: "Gion", text: "Historic lanes of teahouses; respect the no-photo zones." },
      { title: "Kiyomizu-dera", text: "Wooden stage with city views." },
      { title: "Nishiki Market", text: "Kyoto's kitchen for snacks and pickles." },
    ],
    neighborhoods: "Near Kyoto Station for transit, or Gion and Higashiyama for atmosphere.",
    tip: "Buses get crowded; combine trains and walking.",
    airport: "No airport of its own: fly into Kansai (KIX) and take the Haruka express in about 75 min, or Itami (ITM) by limousine bus.",
    gettingAround: "Buses, subway and JR/Keihan trains; rent a bike for flat areas.",
    food: ["Kaiseki", "Matcha sweets", "Yudofu (tofu hot pot)", "Obanzai home cooking", "Nishin soba"],
    currency: "Japanese yen (JPY)", language: "Japanese",
    goodToKnow: ["Private alleys in Gion ban photography.", "Many temples close by 5pm.", "Book blossom and foliage seasons months ahead."],
    tours: [
      { id: "kyoto-highlights", name: "Kyoto's greatest temples", duration: "Full day", summary: "Fushimi Inari, Kinkaku-ji and Kiyomizu-dera with a private guide.", highlights: ["Early-morning Inari", "Private car", "Lunch"] },
      { id: "kyoto-tea", name: "Tea ceremony and kimono", duration: "2 hours", summary: "Traditional tea ceremony in a townhouse, kimono included.", highlights: ["Kimono dressing", "Tea master", "Photo time"] },
      { id: "kyoto-gion", name: "Gion evening walk", duration: "2 hours", summary: "Geisha district history with a licensed guide.", highlights: ["Hanamikoji", "Shirakawa canal", "Etiquette briefing"] },
    ],
  },
];
